# add more stdlib input validation
class influxdb::server::config {
  $version                                      = $influxdb::server::version
  $config_file                                  = $influxdb::server::config_file
  $ensure                                       = $influxdb::server::ensure
  $conf_template                                = $influxdb::server::conf_template
  $influxdb_user                                = $influxdb::server::influxdb_user
  $influxdb_group                               = $influxdb::server::influxdb_group
  $bind_address                                 = $influxdb::server::bind_address
  $retention_autocreate                         = $influxdb::server::retention_autocreate
  $election_timeout                             = $influxdb::server::election_timeout
  $heartbeat_timeout                            = $influxdb::server::heartbeat_timeout
  $leader_lease_timeout                         = $influxdb::server::leader_lease_timeout
  $commit_timeout                               = $influxdb::server::commit_timeout
  $cluster_tracing                              = $influxdb::server::cluster_tracing
  $raft_promotion_enabled                       = $influxdb::server::raft_promotion_enabled
  $meta_dir                                     = $influxdb::server::meta_dir
  $data_dir                                     = $influxdb::server::data_dir
  $wal_dir                                      = $influxdb::server::wal_dir
  $data_engine                                  = $influxdb::server::data_engine
  $wal_enable_logging                           = $influxdb::server::wal_enable_logging
  $wal_ready_series_size                        = $influxdb::server::wal_ready_series_size
  $wal_compaction_threshold                     = $influxdb::server::wal_compaction_threshold
  $wal_max_series_size                          = $influxdb::server::wal_max_series_size
  $wal_flush_cold_interval                      = $influxdb::server::wal_flush_cold_interval
  $wal_partition_size_threshold                 = $influxdb::server::wal_partition_size_threshold
  $max_wal_size                                 = $influxdb::server::max_wal_size
  $wal_flush_interval                           = $influxdb::server::wal_flush_interval
  $wal_partition_flush_delay                    = $influxdb::server::wal_partition_flush_delay
  $query_log_enabled                            = $influxdb::server::query_log_enabled
  $tsm_cache_max_memory_size                    = $influxdb::server::tsm_cache_max_memory_size
  $tsm_cache_snapshot_memory_size               = $influxdb::server::tsm_cache_snapshot_memory_size
  $tsm_cache_snapshot_write_cold_duration       = $influxdb::server::tsm_cache_snapshot_write_cold_duration
  $tsm_compact_min_file_count                   = $influxdb::server::tsm_compact_min_file_count
  $tsm_compact_full_write_cold_duration         = $influxdb::server::tsm_compact_full_write_cold_duration
  $tsm_max_points_per_block                      = $influxdb::server::tsm_max_points_per_block
  $shard_writer_timeout                         = $influxdb::server::shard_writer_timeout
  $cluster_write_timeout                        = $influxdb::server::cluster_write_timeout
  $retention_enabled                            = $influxdb::server::retention_enabled
  $retention_check_interval                     = $influxdb::server::retention_check_interval
  $shard_precreation_enabled                    = $influxdb::server::shard_precreation_enabled
  $shard_precreation_check_interval             = $influxdb::server::shard_precreation_check_interval
  $shart_precreation_advance_period             = $influxdb::server::shart_precreation_advance_period
  $admin_enabled                                = $influxdb::server::admin_enabled
  $admin_bind_address                           = $influxdb::server::admin_bind_address
  $admin_https_enabled                          = $influxdb::server::admin_https_enabled
  $admin_https_certificate                      = $influxdb::server::admin_https_certificate
  $http_enabled                                 = $influxdb::server::http_enabled
  $http_bind_address                            = $influxdb::server::http_bind_address
  $http_auth_enabled                            = $influxdb::server::http_auth_enabled
  $http_log_enabled                             = $influxdb::server::http_log_enabled
  $http_write_tracing                           = $influxdb::server::http_write_tracing
  $http_pprof_enabled                           = $influxdb::server::http_pprof_enabled
  $http_https_enabled                           = $influxdb::server::http_https_enabled
  $http_https_certificate                       = $influxdb::server::http_https_certificate
  $graphite_options                             = $influxdb::server::graphite_options
  $collectd_options                             = $influxdb::server::collectd_options
  $opentsdb_options                             = $influxdb::server::opentsdb_options
  $udp_options                                  = $influxdb::server::udp_options
  $monitoring_enabled                           = $influxdb::server::monitoring_enabled
  $monitoring_write_interval                    = $influxdb::server::monitoring_write_interval
  $continuous_queries_enabled                   = $influxdb::server::continuous_queries_enabled
  $continuous_queries_recompute_previous_n      = $influxdb::server::continuous_queries_recompute_previous_n
  $continuous_queries_recompute_no_older_than   = $influxdb::server::continuous_queries_recompute_no_older_than
  $continuous_queries_compute_runs_per_interval = $influxdb::server::continuous_queries_compute_runs_per_interval
  $continuous_queries_compute_no_more_than      = $influxdb::server::continuous_queries_compute_no_more_than
  $hinted_handoff_enabled                       = $influxdb::server::hinted_handoff_enabled
  $hinted_handoff_dir                           = $influxdb::server::hinted_handoff_dir
  $hinted_handoff_max_size                      = $influxdb::server::hinted_handoff_max_size
  $hinted_handoff_max_age                       = $influxdb::server::hinted_handoff_max_age
  $hinted_handoff_retry_rate_limit              = $influxdb::server::hinted_handoff_retry_rate_limit
  $hinted_handoff_retry_interval                = $influxdb::server::hinted_handoff_retry_interval
  $hinted_handoff_retry_max_interval            = $influxdb::server::hinted_handoff_retry_max_interval
  $hinted_handoff_purge_interval                = $influxdb::server::hinted_handoff_purge_interval
  $reporting_disabled                           = $influxdb::server::reporting_disabled
  $enable_snapshot                              = $influxdb::server::enable_snapshot
  $influxdb_stderr_log                          = $influxdb::server::influxdb_stderr_log
  $influxdb_stdout_log                          = $influxdb::server::influxdb_stdout_log
  $influxd_opts                                 = $influxdb::server::influxd_opts

  file { $config_file:
    ensure  => $ensure,
    content => template($conf_template),
    owner   => $influxdb_user,
    group   => $influxdb_group,
    mode    => '0644',
    notify  => Service['influxdb'],
  }

  file { '/etc/default/influxdb':
    ensure  => $ensure,
    owner   => 'root',
    group   => 'root',
    mode    => '0644',
    content => template('influxdb/influxdb_default.erb'),
    notify  => Service['influxdb'],
  }

}
